### ISSUE TITLE
Unrecognized package dependency type `sdk`

### ISSUE THREAD

**Issue by ScottPierce** [dart-lang/source_gen#126]
My pubspec.yaml for my flutter project:
```
dependencies:
  flutter:
    sdk: flutter
  built_collection: ^1.0.0
  built_value: ^0.5.0

dev_dependencies:
  build: ^0.6.0
  build_runner: ^0.1.0
  built_value_generator: ^0.5.0
  source_gen: '>=0.5.0+03 <0.6.0'
  quiver: '>=0.21.0 <0.24.0'
  test: any
```

I was trying to test `built_value` in my flutter project, and I got this error when I ran the generator:
```
pub run ./tool/watch.dart
Unhandled exception:
Unrecognized package dependency type `sdk`
#0      _dependencyType (package:build_runner/src/package_graph/package_graph.dart:171:7)
#1      PackageGraph.PackageGraph.forPath.addNodeAndDeps.<anonymous closure> (package:build_runner/src/package_graph/package_graph.dart:96:41)
#2      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:348)
#3      PackageGraph.PackageGraph.forPath.addNodeAndDeps (package:build_runner/src/package_graph/package_graph.dart:92:12)
#4      PackageGraph.PackageGraph.forPath (package:build_runner/src/package_graph/package_graph.dart:105:23)
#5      PackageGraph.PackageGraph.forThisPackage (package:build_runner/src/package_graph/package_graph.dart:111:48)
#6      BuildOptions.BuildOptions (package:build_runner/src/generate/options.dart:68:26)
#7      build.<build_async_body> (package:build_runner/src/generate/build.dart:54:21)
#8      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

From the error message, it sounds like `source_gen` doesn't like the usage of `sdk` in my pubspec.yaml
