### ISSUE TITLE
How to make a generator that uses another generator?

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/source_gen#446]
This is more of a question than an issue, but didn't have any success reading the documentation or asking on StackOverflow (see https://stackoverflow.com/questions/59503994/how-to-run-a-code-generator-on-the-top-of-another-code-generator – the answers don't seems to work)

The question is:
How to configure a code-generator when it outputs code that needs to be processed by another generator (json_serializable in my case)?

From what I've seen in another issue, from my understanding `SharedPartBuilder` cannot do this. So I tried a `PartBuilder`, with the following `build.yaml`::

```yaml
builders:
  immutable:
    import: "package:immutable/immutable.dart"
    builder_factories: ["immutable"]
    build_extensions: { ".dart": [".immutable.dart"] }
    auto_apply: all_packages
    build_to: source
    applies_builders: ["json_serializable|json_serializable"]
    runs_before: ["json_serializable|json_serializable"]
```

Which does generate the `.immutable.dart` file, but the `.g.dart` that `json_serializable` is supported to genrate never appears.
