### ISSUE TITLE
Weird behavior when reading part files from different targets

### ISSUE THREAD

**Issue by simolus3** [dart-lang/source_gen#447]
Sorry for the lengthy repro, it's the most minimal I could find. I've uploaded the full sources [here](https://drive.google.com/file/d/1XydiEs-SSHc3o7UTiYsafFNUi4J_9pti/view?usp=sharing), it can be reproduced by running `pub get` and `pub run build_runner build -v`.

I'm trying to solve the same problem as #446, but with build targets instead of applying dependencies on a builder. I have an input file, `source_gen_parts_repro|lib/input.dart`:
```dart
import 'package:built_value/built_value.dart';

part 'input.custom.dart'; // generated by us
part 'input.g.dart'; // generated by source_gen & built_value

abstract class Foo implements Built<Foo, FooBuilder> {
  Bar get bar;

  Foo._();

  factory Foo(void Function(FooBuilder) updates) = _$Foo;
}
```

The class `Bar` will be written into `input.custom.dart`, by the following builder
```dart
import 'dart:async';
import 'package:build/build.dart';

Builder create([BuilderOptions _]) => MyBuilder();

class MyBuilder extends Builder {
  @override
  Future<void> build(BuildStep buildStep) async {
    final input = buildStep.inputId;
    // this is one of those issues that only happens if this line is active:
    await buildStep.resolver.isLibrary(input);

    if (input.path.endsWith('input.dart')) {
      final output = input.changeExtension('.custom.dart');
      print('MyBuilder $input -> $output');
      await buildStep.writeAsString(output, '''
part of 'input.dart';

class Bar {}
      ''');
    }
  }
  @override
  Map<String, List<String>> get buildExtensions => const {
        '.dart': ['.custom.dart']
      };
}
```

Finally, I have my build targets set up so that `MyBuilder` runs before built value:

```yaml
builders:
  source_gen_parts_repro:
    import: "package:source_gen_parts_repro/builder.dart"
    builder_factories: ["create"]
    build_extensions: {".dart": [".custom.dart"]}
    build_to: source

targets:
  $default:
    builders:
      built_value_generator|built_value:
        enabled: false
      source_gen_parts_repro:
        enabled: true
  
  run_built_value:
    dependencies:
      - source_gen_parts_repro
    builders:
      built_value_generator|built_value:
        enabled: true
```

## Problem

First, most of this works! `built_value_generator` doesn't complain about `Bar` not existing anymore. All the outputs looks exactly like I'd expect them to look like. However, the logs contain:
```
[WARNING] source_gen_parts_repro:source_gen_parts_repro on lib/input.dart:
MyBuilder source_gen_parts_repro|lib/input.dart -> source_gen_parts_repro|lib/input.custom.dart
[INFO] Heartbeat:8.3s elapsed, 2/2 actions completed.
[FINE] built_value_generator:built_value on lib/builder.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/input.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/input.custom.dart:Running BuiltValueGenerator
[WARNING] built_value_generator:built_value on lib/input.custom.dart:
Missing "part 'input.custom.g.dart';".
[INFO] Build:Running build completed, took 13.4s
```

As you can see, `source_gen` warns about a missing `part` in `input.custom.dart`. That's unexpected, since the file already contains a `part of` statement and no generators should run on it. This might be another problem with `build_resolvers` and `isLibrary` not returning the right values. Maybe I'm also just using build targets wrong?
