### ISSUE TITLE
Cannot generate source for sub packages

### ISSUE THREAD

**Issue by xujim** [dart-lang/source_gen#525]
hi, I use the source_gen to generate code for more than one packages in my project.
For instance, the packages is A, B, C. C is my code generate SDK based on source_gen, and will be used to generate code for A and B. Both A and B depends on C.
I config the build.yaml in C like following:
```
targets:
  $default:
    builders:
      lite_route|route_builder:
        enabled: true
        generate_for:
          include: ['*.route.dart']
          exclude: ['**.r.dart']
      lite_route|route_write_builder:
        enabled: true
        options: { 'write': true }
        generate_for:
          include: ['*.route.dart']
          exclude: ['**.r.dart']

builders:
  route_builder:
    import: 'package:lite_route/builder.dart'
    builder_factories: ['routeBuilder']
    build_extensions: { '.route.dart': ['.invalid.r.dart'] }
    auto_apply: dependents
    runs_before: ['lite_route|route_write_builder']
    build_to: source

  route_write_builder:
    import: 'package:lite_route/builder.dart'
    builder_factories: ['routeWriteBuilder']
    build_extensions: { '.route.dart': ['.r.dart'] }
    auto_apply: dependents
    build_to: source
```
However, unfortunately, I can only successfully generate code for A, but failed for B.
Could you help? Does source_gen support such feature? I think such feature is necessary.
