### ISSUE TITLE
How to filter input by extension ?

### ISSUE THREAD

**Issue by tolotrasamuel** [dart-lang/source_gen#530]
The buildExtensions in `builder.dart` is `.dart` 

It builds for any dart file

`    buildExtensions = {          '.dart': [generatedExtension]..addAll(additionalOutputExtensions)        },`

<img width="720" alt="Screenshot 2021-05-22 at 12 48 00" src="https://user-images.githubusercontent.com/29230303/119220596-71e09280-bafc-11eb-9a51-6b657cd7dc42.png">

So even if in build.yaml, I set the build input to `.source.dart`

```
  functionUnwrap:
    import: 'package:my_generators/my_generators.dart'
    builder_factories: ['functionUnwrapBuild']
    auto_apply: dependents
    build_extensions: {".source.dart": [".unwrapped.dart"]}
    build_to: source
    applies_builders: ["source_gen"]
```

It ignores the `".source.dart"` and still runs on any dart file.
