### ISSUE TITLE
type 'UnspecifiedInvalidResult' is not a subtype of type 'LibraryElementResult' in type cast

### ISSUE THREAD

**Issue by AlexanderArendar** [dart-lang/source_gen#557]
I use `built_value` package in my project.
Everything was fine till today, when I've added a simple dart class which does not even participate in the built_value generation, and after that an exception occurs when I try to generate built_value classes.

The exception is this:
```
[SEVERE] built_value_generator:built_value on test/pages/case_portal/presenter_workspaсe.dart:

type 'UnspecifiedInvalidResult' is not a subtype of type 'LibraryElementResult' in type cast
package:build_resolvers/src/resolver.dart 216:56  AnalyzerResolver.libraryFor
package:source_gen/src/builder.dart 79:17         _Builder.build
```

My `pubspeck.yaml` is following:
```
name: shimlaw_qa
description: Automated tests for Case Chronology
# version: 1.0.0
# homepage: https://www.example.com
# author: alex <alexander.arendar@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  matcher:
  built_value: ^8.1.2
  built_value_generator: ^8.1.2
  built_collection: ^5.1.1
  yaml:
  collection:
  webdriver: ^3.0.0
  intl:
  tuple:
  http:

dev_dependencies:
  build_runner: ^2.1.4
  lints: ^1.0.1
  test: ^1.18.2
```

The class that it stumbles upon is following:
import '../../models/case.dart';
import 'workspace_page.dart';

```
class PresenterWorkspacePage extends WorkspacePage {
  PresenterWorkspacePage(Case caze) : super(caze);

  @override
  void waitTillPageLoaded() {
    waitUntilVisibleByXpath("//h3[text()='${caze.caseName}']", maxWait: Duration(seconds: 12));
    if (!noPages()) {
      waitUntilVisibleByXpath("//div[contains(@class, 'MuiGrid-item')]");
    }
  }
}
```

Exception happens when I try to run the `pub run build_runner build --verbose` command.
