### ISSUE TITLE
Specify output of generated file through capture groups

### ISSUE THREAD

**Issue by rlch** [dart-lang/source_gen#562]
Hey, according to [this doc](https://github.com/dart-lang/build/blob/master/docs/writing_a_builder.md) you can use capture groups to achieve something like this:

```yaml
builders:
  pearl|entity:
    import: "package:pearl/builder.dart"
    builder_factories: ["entity"]
    build_extensions: { "^{{root}}/domain/entities/{{entity}}.dart": ["{{root}}/data/models/{{entity}}.model.dart"] }
    auto_apply: dependents
    build_to: source
```
which, if I'm not mistaken, would take `lib/src/domain/entities/ex.dart` and output `lib/src/data/models/ex.model.dart`.

@natebosch You mentioned this way back in 2016:
> It's no longer a source_gen limitation but a build limitation that files can only be output directly next to inputs

Is this still true, and if not, how come the `BuildConfig` above still generates `lib/src/domain/entities/ex.model.dart` using a `LibraryGenerator`?
