### ISSUE TITLE
Files only generated in cache(?), not in source tree

### ISSUE THREAD

**Issue by boekhold** [dart-lang/source_gen#570]
Hi all,

```
    • Flutter version 2.5.3 at C:\Maarten\local\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
```

I'm trying to follow the example from Simon Binder (https://simonbinder.eu/posts/build_directory_moves/) on how to place the json_serializable files into a separate directory. What I'm observing is that the generated files do get created, but they are only available under the ".dart_tools/build" directory, they do not show up in the main source tree as expected.

pubspec.yaml (only relevant bits):
```
dependencies:
  json_annotation: ^4.3.0

dev_dependencies:
  build_runner: ^2.1.5
  source_gen: ^1.1.1
  json_serializable: ^6.0.0
```

build.yaml:
```
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
```

All my "json classes" are under `<project root>/lib/api/model`. Expected result is that I see the generated files under `<project root>/lib/generated/api/model`. But they don't show up there. I only see them under `<project root>/.dart_tools/build/generated/<project name>/lib/generated/api/model`.

What am I doing wrong here? Based on other issues I found, I suspect this has something to do with the combining_builder?

**Comment by boekhold** [comment]
Quick follow-up, but I noticed that the files under `<project root>/.dart_tools/build/generated/<project name>/lib/generated/api/model` are actually `part` files, e.g.:

`<project root>/.dart_tools/build/generated/<project name>/lib/generated/api/model/abstract-building-block.json_serializable.g.part`

which I guess means that the "combining" isn't working?

Running in --verbose move, I see for each file:

```
[WARNING] source_gen:combining_builder on lib/api/model/abstract-building-block.dart:
..\..\generated\api\model\abstract-building-block.g.dart must be included as a part directive in the input library with:
    part '..\..\generated\api\model\abstract-building-block.g.dart';
```

which is weird because all my files do have that `part` line correctly (as far as I can tell):

```
part '../../generated/api/model/abstract-building-block.g.dart';
```

**Comment by simolus3** [comment]
Looking at it some more, it sounds like this might be a Windows-specific issue? I don't have a Windows machine to test, does adding this to your pubspec fix the problems?

```yaml
dependency_overrides:
  source_gen:
    git:
      url: https://github.com/simolus3/source_gen.git
      ref: improve-missing-part-handling
      path: source_gen
```
