### ISSUE TITLE
Failed to precompile build script .dart_tool/build/entrypoint/build.dart

### ISSUE THREAD

**Issue by Abenstex** [dart-lang/source_gen#588]
I hope you can help me, because I'm at a total loss right now. So I wanted to make my life easier and create a source code generator for the most basic UI operations I usually need. I setup a project called ui_generator with the following - still very simple - files.
`pubspec.yaml:`
```
name: ui_generator
description: UI Generator Builder
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.2.1
  source_gen: ^1.2.1
  analyzer: '>=2.1.0 <4.0.0'
  annotations:
    path: ../annotations/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
```

`build.yaml`
```
builders:
  ui_generator:
    import: "package:ui_generator/builder.dart"
    builder_factories: [ "uiGenerator" ]
    build_extensions: { ".dart": [ "ui.g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
```

`builder.dart`
```
library ui_generator;

import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';
import 'src/ui_form_generator.dart';

Builder uiGenerator(BuilderOptions options) => PartBuilder([UiFormGenerator()], 'uiGenerator');
```
And the actual generator `ui_form_generator.dart`:
```
import 'package:analyzer/dart/element/element.dart';
import 'package:source_gen/source_gen.dart';
import 'package:annotations/annotations.dart';
import 'package:build/build.dart';

class UiFormGenerator extends GeneratorForAnnotation<UiDescription> {
  @override
  String generateForAnnotatedElement(
      Element element, ConstantReader annotation, BuildStep buildStep) {
    return "// Hey! Annotation found!";
  }
}
```

I import the ui_generator project in my main project as a dev dependency like this:
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.0.1
  mobx_codegen: ^2.0.5+2
  ui_generator:
    path: ../ui_generator/
```
Now the problem is that every time I run flutter pub run build_runner build I get around 20MB of error messages ending in: 
```
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```
The rest of the error output is basically showing that no reference in the standard flutter libs can be found.
