### ISSUE TITLE
Error:  type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by youngchan1988** [dart-lang/source_gen#597]
My `build.yaml`:
```yaml
targets:
  $default:
    builders:
      nc_ui_system|router_scan:
        generate_for:
          - lib/page/**.dart
      nc_ui_system|router_gen:
        generate_for:
          - lib/router/router.dart

builders:
  router_scan:
    import: "package:nc_ui_system/builder.dart"
    builder_factories: ["routerScanBuilder"]
    build_extensions: {".dart": [".none.dart"]}
    runs_before: ["nc_ui_system|router_gen"]
    auto_apply: none
    build_to: source

  router_gen:
    import: "package:nc_ui_system/builder.dart"
    builder_factories: ["routerGenBuilder"]
    build_extensions: {".dart": ["router.g.dart"]}
    auto_apply: none
    build_to: cache
```
When I run `flutter pub run build_runner build`. Then the outputs:

```shell
[INFO] Generating build script...
[INFO] Generating build script completed, took 510ms

[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 6.2s

[SEVERE] 
type 'Null' is not a subtype of type 'String'


```
I don't know what the error is. 

Packages version:
```yaml
  build_runner: ^2.1.10
  source_gen: ^1.2.2
```
