### ISSUE TITLE
Coverage ignore option

### ISSUE THREAD

**Issue by jtdLab** [dart-lang/source_gen#624]
Hi,

is it possible to add an option to combining_builder  which leads to the line `//coverage:ignore-file` beeing added on top of generated files. Or is there already an existing solution?

Something like:

```yaml
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          coverage-ignore-file: true
```
