### ISSUE TITLE
Cannot generate an output file in integration_test folder using source_gen and build_runner

### ISSUE THREAD

**Issue by JasperEssien2** [dart-lang/source_gen#634]
I'm creating a code generation package for widget and integration tests. I've tried including the integration_test folder path in my `build.yaml` file.

```yaml
targets:
  $default:
    builders:
      finder_matcher_gen|finder_matcher_annotation:
        enabled: true

        generate_for:
        - integration_test/**
        - test/**
 

builders:
  finder_matcher_gen:
    import: "package:finder_matcher_gen/builder.dart"
    builder_factories: ["generateFinder", "generateMatcher"]
    build_extensions: {"{{file}.dart": ["generated/{{file}}.finders.dart, generated/{{file}}.matchers.dart"]}
    auto_apply: dependents
    build_to: "source"
```

Files are generated for `test` folders but not for `integration_test`. No error is thrown, just a success message but no new files.

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-include-additional-sources-in-my-build

**Comment by JasperEssien2** [comment]
Hi @jakemac53 

Thanks for your feedback. I've updated my `build.yaml` to this. It still doesn't work.

```yaml
targets:
  $default:
    sources:
      - integration_test/**
      - lib/**
      - pubspec.*
      - $package$
    builders:
      finder_matcher_gen|finder_matcher_annotation:
        enabled: true
 

builders:
  finder_matcher_gen:
    import: "package:finder_matcher_gen/builder.dart"
    builder_factories: ["generateFinder", "generateMatcher"]
    build_extensions: {"{{file}.dart": ["generated/{{file}}.finders.dart, generated/{{file}}.matchers.dart"]}
    auto_apply: dependents
    build_to: "source"

```

 Please can you point to what I'm doing wrong? 

Thank you.
