### ISSUE TITLE
LibraryBuilder should allow more customized build extensions

### ISSUE THREAD

**Issue by Vildnex** [dart-lang/source_gen#692]
* Dart SDK Version: `Dart SDK version: 3.2.1 (stable) (None) on "linux_x64"`
* What package(s) from this repo you are using, and the version:
      - build 2.4.1
      - source_gen 1.4.0
      - build_runner 2.4.6
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do:
      Summary: I am trying to build a builder that is going to generate some files into a custom folder instead of them to be next to the source folder.

Current folder project structure after running that command:

    ├── lib
    │   ├── entity_generator.dart
    │   └── test_files
    │       ├── annotation
    │       │   └── annotation.dart
    │       ├── classes2.dart
    │       ├── classes2.entity.dart
    │       ├── classes.dart
    │       ├── classes.entity.dart
    │       └── gen
    ├── pubspec.lock
    └── pubspec.yaml

Current folder project structure after generating them into the custom folder:

    ├── lib
    │   ├── entity_generator.dart
    │   └── test_files
    │       ├── annotation
    │       │   └── annotation.dart
    │       ├── classes2.dart
    │       ├── classes.dart
    │       └── gen
    │           ├── classes.entity.dart
    |  	        └── classes2.entity.dart
    ├── pubspec.lock
    └── pubspec.yaml

entity_generator.dart:

    class EntityGenerator extends GeneratorForAnnotation<Entity> {
      @override
      generateForAnnotatedElement(Element element, ConstantReader annotation, BuildStep buildStep) {
        if (element is! ClassElement) {
          throw InvalidGenerationSourceError('`@Entity` can only be used on classes.', element: element);
        }
    
        final className = element.displayName;
        final buffer = StringBuffer();
    
        // Generate the class with entity exports
        buffer.writeln('class $className extends Entity {}');
        return buffer.toString();
      }
    }
    
    Builder entityBuilder(BuilderOptions options) => LibraryBuilder(EntityGenerator(), generatedExtension: '.entity.dart');

build.yaml:
```
    targets:
      $default:
        builders:
          test_app|export_locating_builder:
            enabled: true
    
    builders:
      export_locating_builder:
        import: "package:test_app/entity_generator.dart"
        builder_factories: [ "entityBuilder" ]
        build_extensions: {
          '^lib/test_files/{{}}.dart': ['lib/test_files/gen/{{}}.entity.dart']
        }
        auto_apply: dependents
        build_to: source
```

For the moment even if I did the part {{}} the files will still be generated next to the original class instead of the `gen` folder. 

* Whether you are using Windows, MacOSX, or Linux (if applicable):
   `Linux`
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable):
`Not applicable` 
* Any other packages or constraints we should know about
`None`

Sources that I've checked already:

- https://github.com/dart-lang/build/issues/3475
- https://github.com/dart-lang/build/blob/master/docs/writing_a_builder.md#capture-groups
- https://simonbinder.eu/posts/build_directory_moves/
