### ISSUE TITLE
Unable to generate files in a different folder

### ISSUE THREAD

**Issue by bilalrabibi** [dart-lang/source_gen#701]
Using PartBuilder 
i am not able to generate the files in specific folder.

pubspec.yaml
```
dependencies:
  material: 1.0.0+2
  meta: 1.10.0
  source_gen: ^1.4.0

```

 I have tried below in  my project build.yaml file

```
auto_models:
        options:
  
          build_extensions:
            "{{}}.dart": '{{dir}}/generated/{{file}}.mapped.g.dart'

```

full yaml file is 

```
targets:
  $default:
    builders:
      
      
      #general purpose .g.dart builder
      source_gen|combining_builder:
        enabled: true
        
        generate_for:
          - lib/**.dart
        options:
          build_extensions:
            '^{{path}}/{{file}}.dart': '{{path}}/generated/{{file}}.g.dart'

      #chopper
      chopper_generator:
        options:
          # This assumes you want the files to end with `.chopper.g.dart`
          # instead of the default `.chopper.dart`.
          build_extensions:
            "^{{path}}/{{file}}.dart": '{{path}}/generated/{{file}}.chopper.g.dart'
     
 ````

My package yaml file 
```
targets:
  $default:
    builders:
      auto_models|auto_models:
        enabled: true

builders:

  auto_models:
    import: "package:auto_models/builder.dart"
    builder_factories: ["dataModalBuilder"]
    
    build_extensions: { ".dart": [ "generated/.mapped.g.dart" ] }
    auto_apply: dependents
    build_to: source          
    runs_before: ["drift_dev|drift_dev"]
    applies_builders: ["source_gen|combining_builder"]

```

also tried 

```    build_extensions: { ".dart": [ ".mapped.g.dart" ] } ```

but files are always generating inside same folder
